name: CI with Slack Notification

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run tests (example)
      - name: Run Tests
        run: echo "Running tests..."

      # Step 3: Send Slack Notifications (always runs)
      - name: Send Slack Notification
        if: always()   # ensures it runs even if job fails
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 GitHub Action finished!\nRepository: ${{ github.repository }}\nWorkflow: ${{ github.workflow }}\nJob: ${{ github.job }}\nStatus: ${{ job.status }}\nCommit: ${{ github.sha }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
