steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/opensourcetools-poc/gke-simple-app/flask-persist-app:latest', '.']

images:
  - 'asia-south1-docker.pkg.dev/opensourcetools-poc/gke-simple-app/flask-persist-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
