steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/opensourcetools-poc/gke-simple-app/flask-persist-app:$SHORT_SHA'
      - '.'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/opensourcetools-poc/gke-simple-app/flask-persist-app:$SHORT_SHA'

  # Step 3: Clone repo and update deployment.yaml
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    secretEnv: ['GITHUB_TOKEN']
    args:
      - '-c'
      - |
        git config --global user.name "cloud-build-cd"
        git config --global user.email "cd-bot@example.com"
        git clone https://karthiknayakniveus:${GITHUB_TOKEN}@github.com/karthiknayakniveus/simple-app-gke-deployment.git
        cd simple-app-gke-deployment
        sed -i 's|image: .*|image: asia-south1-docker.pkg.dev/opensourcetools-poc/gke-simple-app/flask-persist-app:'"$SHORT_SHA"'|' app-deployment.yaml
        git commit -am "CD: Update image to $SHORT_SHA"
        git push origin main

availableSecrets:
  secretManager:
    - versionName: projects/opensourcetools-poc/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
